# Generated by Django 5.0 on 2024-01-03 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transections', '0002_alter_transaction_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='useraccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount'),
        ),
    ]
