# Generated by Django 5.0 on 2024-01-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_review_email_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1, null=True),
        ),
    ]
